### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by zeliard** [saturday2pm/Server#4]
private only

**Comment by jwvg0425** [comment]
오 제 아이디는 jwvg0425 입니당

**Comment by zeliard** [comment]
@jwvg0425 github아니고 bitbucket ㅋㅋ

**Comment by jwvg0425** [comment]
어.. bitbucket도 jwvg0425인데 이메일 인증이 안 되어있었네요. 아니면 이메일로 적어야하나요? 이메일은  jwvg0425@naver.com 입니다.

**Comment by zeliard** [comment]
@jwvg0425 인비 보냈음 ㅎㅎ 아마도 우리쪽에서 1월쯤에 니네 회사 찾아갈 일이 있을듯.. ㅎㅎ GameLift + VR 게임이 라이브중이라는 것은 아주 좋은 레퍼런스가 될 듯해서

**Comment by pjc0247** [comment]
현욱(22)이 천재야
